version: "3.8"

services:
  nginx:
    container_name: app__nginx
    image: nginx:alpine
    ports:
      - "7000:80"
    volumes:
      - .:/app
      - ./.log/nginx:/var/log/nginx/
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app__network

  app:
    container_name: app__app
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    working_dir: /app
    volumes:
      - .:/app
      - ./.docker/php.ini:/usr/local/etc/php/php.ini
    networks:
      - app__network

  database:
    container_name: app__database
    image: library/mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: cdmllove
      MYSQL_DATABASE: apppp
    volumes:
      - data:/var/lib/mysql
      - ./.docker/mysql.cnf:/etc/mysql/conf.d/custom.cnf
    networks:
      - app__network

  phpmyadmin:
    container_name: app__phpmyadmin
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "7001:80"
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: cdmllove
    networks:
      - app__network

volumes:
  data:
    driver: local

networks:
  app__network:
    driver: bridge
